name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: alvarofgomes
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: profile-3d-contrib.svg
          output_action: commit
